### ISSUE TITLE
"Invalid credentials" alert is sometimes incorrectly shown

### ISSUE THREAD

**Issue by aclissold** [Oakland-University/uMobile-iOS-app#1]
Specifically, [this](https://github.com/Oakland-University/uMobile-iOS-app/blob/228fea8676e2f24e264b245ad8faab52b7e836fc/uMobile/MainViewController.m#L261-L266) alert. The code path that leads to this causes the app to delete stored credentials even though they are valid.

**Comment by asgrant** [comment]
Code is now been committed into the repo.
